/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 22 22:56:15 GMT+08:00 2018
 */

package net.mooctest;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.fail;

import org.junit.Test;
import org.junit.runner.RunWith;

public class Jipa_ESTest {
}
